### ISSUE TITLE
New icon in all reports: let me segment by visitors matching this row's criteria

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#4633]
The goal of this ticket is to create a mechanism to let user view the Visitor Log report filtered to only show visitors matching a given criteria that the Piwik user is interested in.

In particular, in each datatable report that supports it, eg. in the Browsers table, next to the labels eg. "Firefox 33" there is an icon. On click, it opens a popover that shows all visitors that match the segment 'visitor uses browser firefox 33'. 

Another example: viewing the custom variables report you can directly see all users using this particular custom var. Will work the same for Screen resolutions, Keywords, campaigns or any other report.

##### Tasks
- [x] API: Update Metadata APIs to include the information whether a particular metadata report is linked to a segment. For example Referrers.getKeywords returns data from the segment keyword.
  * Proposed: Add a new "segment" entry in the metadata array 
- [x] For each datatable row, if necessary, include the segment value that will match this row (in case it's not simply the label value eg. for browsers a code is used)
- [x] UX: Add new icon in all report tables. The icon is added for all reports where the metadata indicates the report has an equivalent "segment".
- [x] The icon has a tooltip such as "View all Visitors with this Keyword" or "View all visitors who visited this Page URL".
- [x] When clicked, the Visitor Log, segmented to show only those matching the clicked row label, are displayed in the popover.
  * The popover should have meaningful title,
  * maybe include the Segment Editor pre-set to this custom segment?,
  * display the current segment value eg. `Browser is 'Firefox 33'`

##### Implementation
The Visitor Log is filtered to show only visitors matching a given segmentation string:  [learn more about segmentation capability](http://piwik.org/docs/segmentation/) of Piwik. Our [Metadata API](http://developer.piwik.org/api-reference/metadata) also is full featured and in many ways useful. 

For this issue we will 

 * extend the metadata API to make it provide a new flag that says whether the report supports segmentation. 
 * provide for each row, the segment value that will match this particular row / dimension.

Note: this was inspired from the plugin in #3861

**Comment by tsteur** [comment]
Be aware that some reports have multiple segments, eg UserCountry:

```
segments: ["countryCode","continentCode"],
```

In this case we will use the first one. It is not guaranteed that the correct one is always defined first but must do for now

**Comment by tsteur** [comment]
I created an issue asking designers to create icons for it

**Comment by tsteur** [comment]
I will stop working on this issue and discuss further steps with @mattab as a generic solution seems to be not possible. Might work with some changes to Segmentation but then there would be still problems eg how to get the Segmentation display name when a subtable is requested (eg 'test' in '/foo/test' should display '/foo/test' in segmentation title and not only '/test' in case of a subtable). Also metadata in API response gets pretty big etc. Manually defining the segmentation value in row metadata with additional filters is quite hard as well.

**Comment by mattab** [comment]
It's very good we're making progress on this awesome feature. It will take more time to get it right but it's really worth the effort :-) When you have time maybe you can list the next actions and blockers and we will hopefully be able to solve in next few sprints. Exciting!

**Comment by mattab** [comment]
Amazing feature! 

Feedback (WIP):

 * I want to open the Visitor profile from the popover -> how could we make this work well?
 * I somehow want to create in one click, a segment like the one used in the popover, to learn more about this segment of visitors
 * maybe i want to click on the popover somewhere so it opens the visitor log in the main window rather than the popover

**Comment by mattab** [comment]
Got this error:

 * ERROR VisitTime[2015-02-13 11:28:40] [12652] Failed to get data from API: Date format must be: YYYY-MM-DD, or 'today' or 'yesterday' or any keyword supported by the strtotime function (see http://php.net/strtotime for more information): #0 /home/piwik-demo/www/demo.piwik.org/core/Date.php(128): Piwik\Date::getInvalidDateFormatException(false) #1 /home/piwik-demo/www/demo.piwik.org/plugins/VisitTime/API.php(63): Piwik\Date::factory('previous7') #2 [internal function]: Piwik\Plugins\VisitTime\API-&gt;getVisitInformationPerServerTime('1', 'range', 'previous7', false, '1') #3 /home/piwik-demo/www/demo.piwik.org/core/API/Proxy.php(211): call_user_func_array(Array, Array) #4 /home/piwik-demo/www/demo.piwik.org/core/API/Request.php(231): Piwik\API\Proxy-&gt;call('\Piwik\Plugins\...', 'getVisitInforma...', Array) #5 /home/piwik-demo/www/demo.piwik.org/core/ViewDataTable/Request.php(48): Piwik\API\Request-&gt;process() #6 /home/piwik-demo/www/demo.piwik.org/core/Plugin/ViewDataTable.php(327): Piwik\ViewDataTable\Request-&gt;loadDataTableFromAPI(Array) #7 /home/piwik-demo/www/demo.piwik.org/core/Plugin/Visualization.php(177): Piwik\Plugin\ViewDataTable-&gt;loadDataTableFromAPI(Array) #8 /home/piwik-demo/www/demo.piwik.org/core/Plugin/ViewDataTable.php(414): Piwik\Plugin\Visualization-&gt;buildView() #9 /home/piwik-demo/www/demo.piwik.org/core/Plugin/Report.php(317): Piwik\Plugin\ViewDataTable-&gt;render() #10 /home/piwik-demo/www/demo.piwik.org/core/Plugin/Controller.php(328): Piwik\Plugin\Report-&gt;render() #11 /home/piwik-demo/www/demo.piwik.org/plugins/VisitTime/Controller.php(24): Piwik\Plugin\Controller-&gt;renderReport(Object(Piwik\Plugins\VisitTime\Reports\GetVisitInformationPerServerTime)) #12 [internal function]: Piwik\Plugins\VisitTime\Controller-&gt;index() #13 /home/piwik-demo/www/demo.piwik.org/core/FrontController.php(583): call_user_func_array(Array, Array) #14 /home/piwik-demo/www/demo.piwik.org/core/FrontController.php(96): Piwik\FrontController-&gt;doDispatch(NULL, NULL, NULL) #15 /home/piwik-demo/www/demo.piwik.org/core/dispatch.php(31): Piwik\FrontController-&gt;dispatch() #16 /home/piwik-demo/www/demo.piwik.org/index.php(27): require_once('/home/piwik-dem...') #17 {main}

**Comment by tsteur** [comment]
> Re Feedback (WIP)

I suggest to create new issues for all those.

> Rows with Unknown (eg. unknown cities, regions) don't have the icon

That's currently on purpose as some segments don't work when passing an empty label eg `deviceType==` shows "Unknown" and "Desktop". So for the first version the easiest way is to disable it for them instead of showing wrong results in the visitor log. In the next step we can fix the actual segments.

**Comment by tsteur** [comment]
The visitTime error is fixed in a new branch, will pull request once tests are green

**Comment by mattab** [comment]
Further feedback:

 * When clicking in a sub-table such as Event subtable, the [popover such as this one](http://demo.piwik.org/index.php?module=CoreHome&action=index&date=previous7&period=range&idSite=34#/module=Events&action=index&date=previous7&period=range&idSite=34&popover=RowAction$3ASegmentVisitorLog$3AEvents.getActionFromCategoryId$3AeventAction$253D$253Dclick$3A$257B$257D) says  `Visitor Log showing visits where is "click"`  but we expected to be `Visitor Log showing visits where Event action is "click"`
 * The following reports don't have an icon as they don't have yet a segment. We need to create a segment for these:
  *  Device brand 
  *  Device model 
  * Browser language
  * Custom Variables will require a new "generic" custom variable segment, covered in #6031
  * Outlinks and Downloads, requires #4103

 * Icon doesn't display in the following reports 
  * Provider (segment `provider`)
  *  Visits per visit duration  (segment `visitDuration`)
  *  Visits by Visit Number (segment `visitCount`)
  *  Visits per number of pages  (segment `actions`)
  *  Visits by days since last visit (segment `daysSinceLastVisit`)
  * Page title (segment `pageTitle`)  
  * Site Search (segment `siteSearchKeyword`)
  * Referrer type (segment `referrerType`)
 * The popover does not show data when a URL contains exotic characters eg in [this report](http://demo.piwik.org/index.php?module=CoreHome&action=index&date=previous7&period=range&idSite=1#/module=Actions&action=menuGetExitPageUrls&date=previous7&period=range&idSite=1)  the popover does not show data for [/piwik日本ユーザー会について](http://www.piwikjapan.org/piwik%E6%97%A5%E6%9C%AC%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E4%BC%9A%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6), this is [the loaded popover URL](http://demo.piwik.org/index.php?module=CoreHome&action=index&date=previous7&period=range&idSite=1#/module=Actions&action=menuGetExitPageUrls&date=previous7&period=range&idSite=1&popover=RowAction$3ASegmentVisitorLog$3AActions.getExitPageUrls$3AexitPageUrl$253D$253Dhttp$25253A$25252F$25252Fwww.piwikjapan.org$25252Fpiwik$2525E6$252597$2525A5$2525E6$25259C$2525AC$2525E3$252583$2525A6$2525E3$252583$2525BC$2525E3$252582$2525B6$2525E3$252583$2525BC$2525E4$2525BC$25259A$2525E3$252581$2525AB$2525E3$252581$2525A4$2525E3$252581$252584$2525E3$252581$2525A6$3A$257B$257D)
 * In the "Referrers > Search engines" the `Keyword not defined` popover shows all kinds of referrers. Maybe it should segment for Visitors with `referrerType==search`
 * Could we display the icon in the sub-tables of the "Referrers" reports such as Search engines, Search keyword, Websites URLs and Campaign keywords


(I'll create issues for those if you want)

**Comment by tsteur** [comment]
If a segment exists but doesn't show in UI it is either define in `/core` and not in the column directly, or the dimension is not linked with a report, or it is not easy to implement eg in case of pageTitles as it has weird subtables constructions but no `url` metadata. You can create separate issues for all those.

Re search engines will see if it is possible to disable it for Keyword not defined unless segments support to filter exactly this. Filtering for `referrerType==search` would be wrong.

Displaying them in subtables would be a new issue as well as the others.

Re event action this looks like a regression, it was not supposed to be displayed in the subtables there and will remove it again.

I will have a look re the exotic characters but already mentioned to you last week that there is a problem and how Piwik stores them etc.

**Comment by tsteur** [comment]
Re search engine I think what you meant is we always need to append/prepend `referrerType==search` to all of the segment filters

**Comment by mattab** [comment]
Created follow up issues:
 *  Display the "Segmented Visitor Log" icon in more reports #7212 
 *  Display the "Segmented Visitor Log" icon in sub-tables reports #7213

**Comment by mattab** [comment]
> Re event action this looks like a regression, it was not supposed to be displayed in the subtables there and will remove it again.

Ok
