### ISSUE TITLE
Getting build feedback from CI is too slow -> let's make it faster

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6412]
The goal of this issue is to discuss the best ways to ensure that when a developer pushes code to Piwik our CI service will run the builds and provide feedback very quickly, ideally under 20 minutes after pushing

Current challenges

 * [x] **Too many jobs started** - we will reduce the number of jobs in the Travis CI piwik/piwik build. Covered in #6413
 * [ ]  **Travis CI queuing time** - sometimes a build is waiting for 20min or longer causing slow feedback to devs. 
 * [x] **Allow developer to run tests in the Cloud** - to work around this couple team members suggested we run the builds on EC2  #6429 - implemented in #6540

Ideas

 * [ ]  **Tests setup times** - currently we setup the full webserver + python in each suite. Instead we should only setup webserver+extras when running System tests.  Covered in #6312 

Please contribute ideas and suggestions so we can make CI feedback as fast as it should ie. within 10-20min!
