### ISSUE TITLE
Various bugs when using SSL and/or a reverse proxy

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#6880]
The goal of this issue is to investigate various bug reports by users when a [reverse / ssl proxy](http://piwik.org/faq/how-to-install/faq_98/) is used in Piwik.

Reverse proxy / wrong URLs:
- [ ]  Sparklines fail to load behind reverse proxy because of wrong URI #5288 
- [ ] Some URLs not resolved appropriately behind proxy #6644

Proxy issue with SSL:
-  [x] When Real time map is loaded over https, it does not always load the SVG files over ssl #6703 
-  [ ] HTML email reports: Links to Piwik and Icons not working on HTTPS (IP address used instead of hostname) #5250

**Comment by mlissner** [comment]
The documentation seems to indicate that Piwik will work fine behind a proxy:

https://piwik.org/faq/how-to-install/faq_98/

Since there have been known issues for so long, is there any chance that a note could be added there that says which features won't work if you set up Piwik behind a proxy? It'd save people a lot of time. I'm a novice at Apache, and a newb at proxies, and I assumed for a long time that this was my misconfiguration, before realizing I should maybe search Piwik's issues.

**Comment by mattab** [comment]
Hi, Since #12011  was merged, we consider this issue fixed. Please check the FAQ here for more information: https://piwik.org/faq/how-to-install/faq_98/

Feedback welcome!

Only remaining issue open is https://github.com/piwik/piwik/issues/5250 which we'll fix soon
