### ISSUE TITLE
Refresh Piwik design and interface

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#7585]
Our goal is to create the best analytics platform. As part of creating a great platform, design and UI is very important to us. The goal of this issue is to refresh the Piwik design and user interface.

Sub-tasks:
 * [x] New design for maintenance mode #7648
 * [x] New design for error pages #7578
 * [x] New design for Updater #7450 
 * [x] New design for Installer #7584 
 * [x]  New design for Marketplace (in Administration) #7586 
 * [x] Design tweaks #8035
 * [x] New design for Administration screens #7587
 * [x]  New Piwik design when main menu is on the left #7589 
 * [x]  Use the "Left Menu" as default menu for all Piwik users #7169
 * [x] Update some icons #7618

**Comment by mattab** [comment]
This project was completed in Piwik 2.15.0! Well done! :rocket:
