### ISSUE TITLE
Refactor tracker code so tracking code that handles request parameters can be organized by plugins

### ISSUE THREAD

**Issue by diosmosis** [piwik/piwik#8071]
The purpose of this issue is to refactor the tracker so code relevant to plugins (eg, goal/conversion tracking, action tracking, etc.) are put into their respective plugins (eg, Goals, Actions).

To accomplish this, we can refactor `Visit::handle()` and introduce a new concept of a `RequestProcessor` which plugins implement to handle tracker request parameters. Unlike dimensions, these parameters do not have to be stored in the DB, and unlike Handlers, these parameters do not require an entirely different tracking mechanism (ie, QueuedTracking).

TODO: 

* [x] introduce a new RequestProcessor interface which plugins implement (and add to DI). has the following methods:
     - processRequestParams(VisitProperties properties, Request request): implementations get information from request and store in visit properties (things like Actions detected, is manual goal conversion, is ecommerce, etc.). VisitProperties is a new class to be introduced, stores variables currently local vars in Visit::handle() or stored as properties in GoalManager.
     - handleRequest(VisitProperties properties): deduce other visit properties based on detected request information (eg, is new visit, goals converted due to action in request, etc.).
     - afterVisitHandled(VisitProperties properties): do non visit related things (like record conversions).
* [x] use the RequestProcessors in Visit::handle() as follows:
     - call processRequestParams() on all request processors to get info from request
     - recognize visitor, turn list of actions into single action (this is done in Action::factory)
     - call handleRequest() on all request processors to determine if visit is new, + other stuff needed
     - handle visit (either existing or new)
     - handle action
     - call afterVisitHandled()
* [x] move goal tracking code to Goals plugin & move action tracking code to Actions plugin
* [x] Move ping=1 tracker handling to a new plugin. When doing so, make sure ping=1 will ignore all goal related logic to be faster.

* [ ] Move Action class & related code to Actions plugin. Move GoalManager to Goals plugin. Move other plugin related code to plugins from core.
* [ ] Move current code to insert/update visit data in core to CoreHome. To do this correctly, would need a new service (eg, VisitRecorder), so VisitRequestProcessor does not get bloated (or more bloated).
* [ ] Remove lots of tracking events, I think many (if not most) are no longer needed.
* [ ] Create a new method in RequestProcessor specifically for manipulating request metadata. Right now, `afterRequestProcessed()` is used for both defining metadata that depends on other plugins' metadata and for manipulating other plugins' metadata. This means metadata that uses other plugins' metadata, can't be manipulated. Order of plugins will be come a problem eventually if many plugins get involved together...
* [ ] Refactor the system again for clarity and ease of use. This makes it possible to split up the code and correctly scope classes, but the code is still verbose and the tracking logic is still not obvious. Before the system is made `@api` it should be made as easy to use as possible.
* [ ] After it is possible to inject "component" types, RequestProcessors should use the "component" scheme.
* [ ] Decouple VisitorRecognizer from Tracker classes and add integration test for it.
* [ ] Do not use multi-dimensional array of properties for request metadata, instead use array of classes defined by plugins, so:

  ```
  /** @var $data MyPluginRequestMetadata */
  $data = $request->getMetadata('MyPlugin');
  ```

**Comment by mnapoli** [comment]
Sounds very good.

Why do the `RequestProcessor` need the 3 separate methods? Could you explain why all that they contain can't be done in one method?

**Comment by diosmosis** [comment]
> Why do the RequestProcessor need the 3 separate methods? Could you explain why all that they contain can't be done in one method?

The current logic (all in `Piwik\Tracker\Visit::handle()`) requires it. At least it's required to separate action + goals logic. For example, actions have to be determined before URL matching goals can be converted. But, manual goal conversion and ecommerce conversion has to be detected before actions, because in this case we don't record an action. This is the reason for `processRequestParams()/handleRequest()`, the first just gets info from the request (ie, actions in request, is it a goal conversion?, is it an ecommerce conversion?) then the second uses that information to deduce more info (based on the actions, is it a goal conversion?).

The third method exists because inserting custom logs has to be done after visits are handled. So recording actions is done after a visit, and recording conversions after the visit.

I don't want to change existing tracker behaviour in any way, just reorganize it.

**Comment by mattab** [comment]
+1 for the general idea to move more logic from Tracker core into the plugins. I really hope we can make it happen for 3.0.0!

**Comment by mnapoli** [comment]
Thanks for the explanation. Regarding the fact that this interface will be implemented by plugins, it might make sense to make it an abstract class instead (to allow a little more flexibility later to add new methods)?

**Comment by diosmosis** [comment]
Abstract class sounds ok to me :)

**Comment by mattab** [comment]
> make sure ping=1 will ignore all goal related logic to be faster.

done in #8223

**Comment by mattab** [comment]
@diosmosis after we make it API (or some of it), can you please check the developer guides cover this new official ways of extending Tracker? https://github.com/piwik/developer-documentation/pull/100/files

**Comment by mattab** [comment]
Part of the issue was done, the rest is "wontfix" until we need it. Likely we'll refactor these Tracker APIs in a later major Piwik version
