### ISSUE TITLE
Release Piwik 2.14.0

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#8198]
Tasks

* [x] Write changelog (@mattab) - https://piwik.org/changelog/piwik-2-14-0/
* [x] Update translations from ~~otrance~~ transifex (@sgiehl)
* [x] Update referrer spam list 
* [x] Update developer changelog:
  * add  `--force-idsegments` and `--skip-idsegments`  from #7912
  * add new `language` segment #3950
  * new task argument to `scheduled-tasks:run` to run a particular task #8186
  * add that it's now possible to use @= operator for userId  #8062
* [x] Create follow up issue to #5287 -> ultimately we want to enable it by default, a new issue will make sure we don't forget that it's not enabled by default yet
* [x] Document `enableHeartBeatTimer` in JavaScript tracking client doc: http://developer.piwik.org/api-reference/tracking-javascript #8071
* [x] Document `enableLinkTracking` changes in JavaScript tracking client doc: http://developer.piwik.org/api-reference/tracking-javascript #8068
* [x] Change changelog published date to the release day

**Comment by mattab** [comment]
* [ ] Update developer changelog:
  * add  `--force-idsegments` and `--skip-idsegments`  from #7912
  * add new `language` segment #3950
  * add that it's now possible to use @= operator for userId  #8062
 * [ ] Create follow up issue to #5287 -> ultimately we want to enable it by default, a new issue will make sure we don't forget that it's not enabled by default yet

**Comment by sgiehl** [comment]
I've just updated the translations

**Comment by mattab** [comment]
* [ ] Document `enableHeartBeatTimer` in JavaScript tracking client doc: http://developer.piwik.org/api-reference/tracking-javascript

**Comment by mattab** [comment]
@diosmosis documented the feature in https://github.com/piwik/developer-documentation/commit/2d9fa991657adc5430b3e80d94ae37ed9ca85304 - please review/edit as you see fit

**Comment by mattab** [comment]
2.14.0 has been released :-) https://piwik.org/changelog/piwik-2-14-0/

This is one very beautiful release! Well done everyone
