### ISSUE TITLE
Make Piwik 3.0 branch master

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik#9096]
We have released the last minor release for Piwik 2.X and from now on there will be only patch releases that contain only important bug and security fixes for 2.15.X.

This means it is time to merge `3.0` => `master` and we will handle `2.15.X` updates in another branch. 

I'm wondering what the normal process for this is? I presume we should release a blog post asap to announce this change as some might have installed `master` via Git on development, testing, QA or production servers. We recommended to not use Piwik via Git so we should be fine here but possibly still need to notify users. 
- Some custom plugins will become incompatible most likely
- If someone uses PHP 5.3 Piwik and updates via Git won't work anymore 
- We also need to mention that Piwik 3.0 API's are not stable yet and there will be changes over time

Before we release a blog post about merging 3.0 we need to:
- [ ] Make Developer Changelog nice (group similar changes etc)
- [ ] Ideally we have some migration guides that makes it easier to update plugins, this should safe a lot of time when updating plugins
- [x] Decide whether we go with PHP5.4 or PHP 5.5 https://github.com/piwik/piwik/issues/8156
- [ ] Make a decision re MySQL support: https://github.com/piwik/piwik/issues/9107

Before merging Piwik 3.0 into master we need to:
- [ ] Make all submodule plugins compatible with 3.0 (eg https://github.com/piwik/plugin-AnonymousPiwikUsageMeasurement/issues/14)

How much time should we give after the blog post till we merge `3.0` => `master`. 2 weeks?

Meanwhile:
We have to issue all PR's for `3.0` and not `master`. If we need a fix for `2.X` we should cherry-pick

**Comment by mattab** [comment]
Moving to 3.0.0-b1

**Comment by sgiehl** [comment]
Can't that one be closed? We already have made 3.x-dev to new master...

**Comment by tsteur** [comment]
👍
