### ISSUE TITLE
JavaScript tracker code should be added immediately before the closing </head> section 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9341]
This issue is about improving our documentation: sometimes we recommend to add the tracking code before `</body>` and sometimes after `<body>`.

Actually it is recommended to include the tracking code in the `<head>` section or after the opening `<body>` tag.

Guides to fix:
 * [x]  FAQ http://piwik.org/faq/new-to-piwik/faq_64/
 * [x] http://developer.piwik.org/api-reference/tracking-javascript in https://github.com/piwik/developer-documentation/commit/878d8bc4fa9bf409a2880dcd24a4fadcde81473b
 * [x] Piwik app during install https://raw.githubusercontent.com/piwik/piwik-ui-tests/master/Installation_js_tracking.png and in the admin screen: https://github.com/piwik/piwik-ui-tests/blob/master/UIIntegrationTest_admin_manage_tracking_code.png

**Comment by gaumondp** [comment]
The logic for suggesting to add code after the `</body>` was that incomplete transmitted pages wouldn't be in the stats. What changed since the original recommendation ?

**Comment by hpvd** [comment]
I think this topic is really important!
From setting up several websites using piwik, we learned the lessons to *load piwik as late as possible.*
The reason is, when people uses browser, browser plugins or browser settings which blocks tracking tools, there is a good chance that everything after the blocked content (piwik) get damaged too.
This leads to a complete broken website.
This is the worst experience on can give a visitor.

If piwik is loaded late -after most of the visible content-and it is blocked in a bad way, the website still look mostly fine.

**Comment by hpvd** [comment]
just a feedback:
As mentioned putting piwik as late as possible was the lessons learned from having problems with some tracking blockers...
For us this does not mean at end of head but at end of body.

This is how to looks:

    
        <script type="text/javascript">
            //<![CDATA[
            ...
        

        </div>
</div>
</body>
</html>

**Comment by novahyth** [comment]
@OP: This suggestion leads to having the fallback code (<noscript><p><img>...</p></noscript>) inside the <head>. It should mention that the fallback code is to be placed inside the <body>.

**Comment by tsteur** [comment]
@novahyth good point, I just realized this as well while having a look at https://github.com/piwik/piwik/issues/9770 . It's not valid HTML otherwise and might not even be executed. I'll create a new issue for this.

**Comment by MattiSG** [comment]
So, why was this done? I thought that webperf dictated to include all scripts as late as possible in the page, and especially the non-critical ones. Analytics is clearly the least to me. Why should I block rendering by adding Piwik in `<head>` rather than before the closing `</body>`?
