### ISSUE TITLE
Better document how to measure Domains, Sub-domains, or a mix of both, and how to correctly configure the JavaScript tracker with setDomains, setCookieDomain and setCookiePath

### ISSUE THREAD

**Issue by mattab** [piwik/piwik#9932]
* [x] When `setDomains` is used, let's remove the magic functionality to automatically set the cookie path. PR https://github.com/piwik/piwik/pull/9933
 * [x] `setDomains` method should support page wildcards matching: `example.com/index*`. PR: https://github.com/piwik/piwik/pull/9979 and Doc: https://github.com/piwik/developer-documentation/pull/122
 * [x] Let's improve the Developer Guide here: http://developer.piwik.org/guides/tracking-javascript-guide#tracking-one-domain - (PR: https://github.com/piwik/developer-documentation/issues/121 + more commits)
 * [x] Add automated test that checks that `getCookieName` depends on the website ID - done in https://github.com/piwik/piwik/commit/81c48b897b4d465a90b0715a9f12daf0e2df7a3d 
 * [x] Update FAQ [tracking multiple sites](http://piwik.org/faq/new-to-piwik/faq_104/)
 * [x] mention useful [InterSites plugin](http://plugins.piwik.org/InterSites) 
 * [x] is there any quick improvement we could make to Tracking JS code generator? or maybe link more clearly to this new doc we're improving here
 * [x] Possibly we could improve our APIs, if so, we could create a follow up issue. For example do we really need setCookiePath along with setCookieDomain? Maybe setCookieDomain could accept a cookie path. --- issue created in https://github.com/piwik/piwik/issues/9980 
 * [x] All PRs linked here are merged

**Comment by mattab** [comment]
>  When setDomains is used, let's remove the magic functionality to automatically set the cookie path

PR: #9933

**Comment by mattab** [comment]
> can I use setCookieDomain with url such as ec.europa.eu/subdirectory ?

Idea: to simplify our JS API, maybe we could 
 * deprecate `setCookiePath` (and remove from docs)
 * let user to use `setCookieDomain` and improve this function so it also works with path

Remove this API function would make understanding things slightly easier.

**Comment by mattab** [comment]
All sub tasks done.
